# Generated by Django 4.1.5 on 2023-03-16 03:16

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address_line_1",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="address_line_2",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="verified",
            field=models.CharField(
                choices=[("Unverified", "Unverified"), ("Verified", "Verified")],
                default="Unverified",
                max_length=20,
                verbose_name="Verified",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="zipcode",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                default="Medellín", max_length=30, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="Colombia", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_buyer",
            field=models.BooleanField(
                default=False,
                help_text="Are you looking to Buy a Product?",
                verbose_name="Buyer",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_seller",
            field=models.BooleanField(
                default=False,
                help_text="Are you looking to sell a product?",
                verbose_name="Seller",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="license",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Shop Eline license"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+573242042421",
                max_length=30,
                region="CO",
                verbose_name="Phone Number",
            ),
        ),
    ]
