# Generated by Django 4.1.5 on 2023-03-18 18:32

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_address_line_1_profile_address_line_2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address_line_1",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="address_line_2",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="verified",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="zipcode",
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                default="Nairobi", max_length=180, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="KE", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_buyer",
            field=models.BooleanField(
                default=False,
                help_text="Are you looking to Buy a Property?",
                verbose_name="Buyer",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_seller",
            field=models.BooleanField(
                default=False,
                help_text="Are you looking to sell a property?",
                verbose_name="Seller",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="license",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Real Estate license"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+41524204242",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
