# Generated by Django 4.1.5 on 2023-03-19 19:28

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_remove_profile_address_line_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(default="Cali", max_length=180, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="CO", max_length=2, verbose_name="Country"
            ),
        ),
    ]
