# Generated by Django 4.1.5 on 2023-03-19 22:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_profile_city_alter_profile_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address_line_1",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="address_line_2",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="verified",
            field=models.CharField(
                choices=[("Unverified", "Unverified"), ("Verified", "Verified")],
                default="Unverified",
                max_length=20,
                verbose_name="Verified",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="zipcode",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+573142544178",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
