# Generated by Django 4.1.5 on 2023-03-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_profile_address_line_1_profile_address_line_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address_line_2",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
