# Generated by Django 4.1.5 on 2023-03-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_profile_address_line_1_profile_address_line_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="departamento",
            field=models.CharField(
                default="Valle del Cauca", max_length=180, verbose_name="Departamento"
            ),
        ),
    ]
