# Generated by Django 4.1.5 on 2023-05-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_profile_departamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="/profile_default.png",
                null=True,
                upload_to="",
                verbose_name="Profile Photo",
            ),
        ),
    ]
